#!/bin/csh -f

# Back up results of training
set backup_str = `date | awk '{print $6$2$3}'`
#set backup_str = 2016Dec7

if ($#argv != 2) then
  set sh = 300
  set sw = 300
else
  set sh = $argv[1]
  set sw = $argv[2]
endif

@ count = `/bin/ls models/ZFNet/DVIADETDB | grep "SSD_${sw}x${sh}.$backup_str" | grep -c 'mark'`
if ( $count == 0 ) then
  set backup_str = ${backup_str}."mark1"
else
  @ str =  `/bin/ls models/ZFNet/DVIADETDB | grep "SSD_${sw}x${sh}.$backup_str" | grep 'mark' | sed 's#.*mark##'` + 1
  set backup_str = ${backup_str}."mark$str"
endif

echo "Backing up results for ZF - DVIADETDB into $backup_str suffix into models, jobs and results directories"

foreach dir ( models/ZFNet/DVIADETDB jobs/ZFNet/DVIADETDB /IMAGESETS/DVIADetDB/DVIAdevkit/results_ssd_zf/DVIADETDB )
  if ( -d "$dir/SSD_${sw}x${sh}" ) then
    set cmd = ( cp -r $dir/SSD_${sw}x${sh} $dir/SSD_${sw}x${sh}.$backup_str )
    echo $cmd
    $cmd
  endif
end
