#!/bin/csh -f

# Back up results of training
set backup_str = `date | awk '{print $6$2$3}'`

set sh = 200
set sw = 150
@ count = `/bin/ls models/ZFNet/VOC0712 | grep "SSD_${sw}x${sh}.$backup_str" | grep -c 'mark'`
if ( $count == 0 ) then
  set backup_str = ${backup_str}."mark1"
else
  @ str =  `/bin/ls models/ZFNet/VOC0712 | grep "SSD_${sw}x${sh}.$backup_str" | grep 'mark' | sed 's#.*mark##'` + 1
  set backup_str = ${backup_str}."mark$str"
endif

echo "Backing up results into $backup_str suffix into models, jobs and results directories"
#exit

foreach dir ( models/ZFNet/VOC0712 jobs/ZFNet/VOC0712 /opt/imagesets/VOCdevkit/results/VOC2007/ZF )
  if ( -d "$dir/SSD_${sw}x${sh}" ) then
    set cmd = ( cp -r $dir/SSD_${sw}x${sh} $dir/SSD_${sw}x${sh}.$backup_str )
    echo $cmd
    $cmd
  endif
end
