#!/bin/csh -f

# Back up results of training
echo "Removing previous training outputs for ZF-VOC from models, jobs and results directories"

set sh = 200
set sw = 150
foreach dir ( models/ZFNet/VOC0712 jobs/ZFNet/VOC0712 /opt/imagesets/VOCdevkit/results/VOC2007/ZF )
  if ( -d "$dir/SSD_${sw}x${sh}" ) then
    set cmd = ( rm -rf $dir/SSD_${sw}x${sh} )
    echo $cmd
    $cmd
  endif
end
