#!/bin/csh -f

# Back up results of training
echo "Removing prevous training outputs from models, jobs and results directories"

foreach dir ( models/ZFNet/VOC0712 jobs/ZFNet/VOC0712 /opt/imagesets/VOCdevkit/results/VOC2007/ZF )
  if ( -d "$dir/SSD_300x300" ) then
    set cmd = ( rm -rf $dir/SSD_300x300 )
    echo $cmd
    $cmd
  endif
end
