#!/bin/csh -f

# Back up results of training
echo "Removing prevous training outputs from models, jobs and results directories for DVIADetDB"

if ($#argv != 2) then
  set sh = 300
  set sw = 300
else
  set sh = $argv[1]
  set sw = $argv[2]
endif

foreach dir ( models/ZFNet/DVIADETDB jobs/ZFNet/DVIADETDB /IMAGESETS/DVIADetDB/DVIAdevkit/results_ssd_zf/DVIADETDB )
  if ( -d "$dir/SSD_${sw}x${sh}" ) then
    set cmd = ( rm -rf $dir/SSD_${sw}x${sh} )
    echo $cmd
    $cmd
  endif
end
