#!/bin/csh -f

# Back up results of training
echo "Removing previous training outputs for ZF-VOC from models, jobs and results directories"

if ($#argv != 2) then
  set sh = 300
  set sw = 300
else
  set sh = $argv[1]
  set sw = $argv[2]
endif

foreach dir ( models/ZFNet/VOC0712 jobs/ZFNet/VOC0712 /opt/imagesets/VOCdevkit/results/VOC2007/ZF )
  if ( -d "$dir/SSD_${sw}x${sh}" ) then
    set cmd = ( rm -rf $dir/SSD_${sw}x${sh} )
    echo $cmd
    $cmd
  endif
end
