#!/bin/csh -f

## SSD Caffe needs GCC 5
setenv CC gcc-5
setenv CXX g++-5
setenv PYTHONPATH $cwd/python

alias chkst 'if ($status != 0) then \
  echo "Failure!"; \
  exit(1); \
endif'
set cdir = `pwd`
set prefix = '/usr/local/caffe-ssd'

set ver=1.0.0-ssd
echo "This will install Caffe SSD " $ver

#goto LDCONFIG
#goto BUILD
#cd build && goto INSTALL || exit (1)
sudo apt-get -y install --install-recommends libatlas3-base libatlas3-base libatlas-dev libatlas-base-dev 
sudo apt-get -y install libboost-dev libboost-filesystem-dev 
# Caffe SSD needs boost_regex
sudo aptitude install libboost-regex-dev
sudo apt-get -y install --install-recommends libprotobuf-dev protobuf-compiler python-protobuf 
sudo apt-get -y install --install-recommends libgoogle-glog-dev libgflags-dev libhdf5-dev liblmdb-dev liblmdb0 lmdb-doc 
sudo apt-get -y install --install-recommends snappy libsnappy-dev libleveldb-dev python-leveldb

BUILD:
cd $cdir
if (! -d build) mkdir build
cd build
#goto MAKE
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$prefix ..

MAKE:
make -j8
chkst
make pycaffe
chkst
make -j8 test
chkst
#make runtest
#chkst

INSTALL:
##--sudo make install
sudo checkinstall --nodoc --strip=yes --backup=no \
        --default \
        --pkgname=caffe-ssd \
        --pkgversion=${ver} \
        --requires=libatlas3-base,libatlas3-base,libatlas-dev,libatlas-base-dev,libboost-dev,libboost-filesystem-dev,libprotobuf-dev,protobuf-compiler,python-protobuf,libgoogle-glog-dev,libgflags-dev,libhdf5-dev,liblmdb-dev,liblmdb0,lmdb-doc,snappy,libsnappy-dev,libleveldb-dev,python-leveldb

chkst


LDCONFIG:
##--set ldstr = ( echo "${prefix}/lib" )
##--sudo sh -c "$ldstr > /etc/ld.so.conf.d/caffe-fast-rcnn.conf"
##--sudo ldconfig
echo "Caffe-ssd" $ver "ready to be used"
